# Generated by Django 3.2.7 on 2022-07-01 19:13

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_hy', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_hy', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Հղում')),
                ('breadcrumbs_text', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_hy', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_ru', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_en', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_image', core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Breadcrumb -ի Նկար')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
            ],
            options={
                'verbose_name': 'Տեսահոլովակի բաժին',
                'verbose_name_plural': 'Տեսահոլովակի բաժիններ',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, verbose_name='Տեսահոլովակի հղում')),
                ('video_file', models.FileField(blank=True, upload_to='', verbose_name='Տեսահոլովակ')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.videocategory')),
            ],
            options={
                'verbose_name': 'Տեսահոլովակ',
                'verbose_name_plural': 'Machanents TV',
                'ordering': ['my_order'],
            },
        ),
    ]
