# Generated by Django 3.2.7 on 2022-07-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել գլխավոր էջում՝ «Machanents TV» սլայդերում'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.videocategory', verbose_name='Բաժին'),
        ),
    ]
