# Generated by Django 3.2.7 on 2022-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20220716_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_iframe',
            field=models.TextField(blank=True, verbose_name='Տեսահոլովակի Iframe'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Տեսահոլովակ (ֆայլ)'),
        ),
    ]
