# Generated by Django 3.2.7 on 2022-07-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Արժույթի անուն')),
                ('icon', models.CharField(max_length=2, unique=True, verbose_name='Լոգո')),
            ],
            options={
                'verbose_name': 'Արժութ',
                'verbose_name_plural': 'Արժութներ',
            },
        ),
        migrations.CreateModel(
            name='DonationHomepageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, verbose_name='Տեքստ')),
                ('text_hy', models.TextField(blank=True, null=True, verbose_name='Տեքստ')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Տեքստ')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Տեքստ')),
                ('background_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ֆոնային նկար')),
            ],
            options={
                'verbose_name': 'Նվիրատվության տեքստ և նկար',
                'verbose_name_plural': 'Նվիրատվության տեքստ և նկար',
            },
        ),
        migrations.CreateModel(
            name='DonationRanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Գումարի չափ')),
                ('currency_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donation.donationcurrencies', verbose_name='Արժույթ')),
            ],
            options={
                'verbose_name': 'Գումար',
                'verbose_name_plural': 'Գումար',
            },
        ),
    ]
