# Generated by Django 3.2.7 on 2022-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donationcurrencies_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcurrencies',
            name='name_en',
            field=models.CharField(db_index=True, max_length=120, null=True, unique=True, verbose_name='Արժույթի անուն'),
        ),
        migrations.AddField(
            model_name='donationcurrencies',
            name='name_hy',
            field=models.CharField(db_index=True, max_length=120, null=True, unique=True, verbose_name='Արժույթի անուն'),
        ),
        migrations.AddField(
            model_name='donationcurrencies',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=120, null=True, unique=True, verbose_name='Արժույթի անուն'),
        ),
    ]
