# Generated by Django 3.2.7 on 2022-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20220716_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcurrencies',
            options={'ordering': ['my_order'], 'verbose_name': 'Արժութ', 'verbose_name_plural': 'Արժութներ'},
        ),
        migrations.AlterModelOptions(
            name='donationhomepagetext',
            options={'ordering': ['my_order'], 'verbose_name': 'Նվիրատվության տեքստ և նկար', 'verbose_name_plural': 'Նվիրատվության տեքստ և նկար'},
        ),
        migrations.AddField(
            model_name='donationhomepagetext',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
    ]
