# Generated by Django 3.2.7 on 2022-07-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20220716_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcurrencies',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='donationcurrencies',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='donationcurrencies',
            name='name_ru',
        ),
    ]
