# Generated by Django 3.2.7 on 2022-07-16 11:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20220716_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhomepagetext',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='donationhomepagetext',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='donationhomepagetext',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='donationhomepagetext',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Տեքստ'),
        ),
    ]
