# Generated by Django 3.2.7 on 2022-07-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20220716_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationRanges',
        ),
    ]
