# Generated by Django 3.2.7 on 2022-07-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_delete_donationranges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Գումարի չափ')),
                ('currency_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='donation.donationcurrencies', verbose_name='Արժույթ')),
            ],
            options={
                'verbose_name': 'Գումար',
                'verbose_name_plural': 'Գումար',
            },
        ),
    ]
