# Generated by Django 3.2.7 on 2022-07-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_donationranges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationhomepagetext',
            options={'verbose_name': 'Նվիրատվության տեքստ և նկար', 'verbose_name_plural': 'Նվիրատվության տեքստ և նկար'},
        ),
        migrations.RemoveField(
            model_name='donationhomepagetext',
            name='my_order',
        ),
    ]
