# Generated by Django 3.2.7 on 2022-07-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Կատարված'),
        ),
    ]
