# Generated by Django 3.2.7 on 2022-07-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_alter_donations_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'ordering': ['-id'], 'verbose_name': 'Նվիրատվություն', 'verbose_name_plural': 'Նվիրատվություններ'},
        ),
    ]
