# Generated by Django 3.2.7 on 2022-07-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_alter_donations_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhomepagetext',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='donationhomepagetext',
            name='title_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='donationhomepagetext',
            name='title_hy',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='donationhomepagetext',
            name='title_ru',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
