# Generated by Django 3.2.7 on 2021-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
    ]
