# Generated by Django 3.2.7 on 2022-07-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220703_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='region',
        ),
    ]
