# Generated by Django 3.2.7 on 2022-07-02 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0008_auto_20220702_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusrequest',
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactusrequest',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contactusjoinusdata',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'svg', 'png', 'jpeg'])], verbose_name='Նկար'),
        ),
    ]
