# Generated by Django 3.2.7 on 2021-10-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_viewedproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewedproducts',
            old_name='product',
            new_name='products',
        ),
    ]
