# Generated by Django 3.2.7 on 2021-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_product_viewedproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_hy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_ru',
            field=models.URLField(blank=True, null=True),
        ),
    ]
