# Generated by Django 3.2.7 on 2021-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211014_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icon/'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
