# Generated by Django 3.2.7 on 2021-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211014_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('icon', models.FileField(upload_to='advantages/')),
                ('title', models.CharField(blank=True, max_length=155)),
                ('my_order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
