# Generated by Django 3.2.7 on 2021-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211014_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialofferbanner',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialofferbanner',
            name='text',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialofferbanner',
            name='text_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialofferbanner',
            name='text_hy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialofferbanner',
            name='text_ru',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
