# Generated by Django 3.2.7 on 2021-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211014_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialofferbanner',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialofferbanner',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialofferbanner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
