# Generated by Django 3.2.7 on 2021-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211014_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingproduct',
            name='ip',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
