# Generated by Django 3.2.7 on 2021-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_ratingproduct_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
