# Generated by Django 3.2.7 on 2021-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='category_image/'),
        ),
    ]
