# Generated by Django 3.2.7 on 2021-10-17 09:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('page', models.CharField(choices=[('service', 'Service'), ('privacy', 'Privacy Policy'), ('contacts', 'Contact Us'), ('faq', 'FAQ'), ('blog', 'Blog'), ('abouts', 'About Us'), ('catalog', 'Catalog'), ('gallery', 'Gallery'), ('sale', 'Sale'), ('search', 'Search'), ('wishlist', 'Wish list'), ('new_products', 'New Products'), ('best_seller', 'Best seller')], max_length=100)),
                ('breadcrumb_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('breadcrumb_image', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
