# Generated by Django 3.2.7 on 2021-10-17 22:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_breadcrumbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAndPayMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_hy', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_hy', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('text_hy', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
