# Generated by Django 3.2.7 on 2021-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_deliveryandpayment_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouradvantages',
            name='title_en',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='title_hy',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='title_ru',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
