# Generated by Django 3.2.7 on 2021-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20211022_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='breadcrumb_image',
            field=models.FileField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='category_image/default.jpg', upload_to='category_image/'),
        ),
    ]
