# Generated by Django 3.2.7 on 2021-10-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20211023_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['my_order'], 'verbose_name': 'Ապրանքի նկար', 'verbose_name_plural': 'Ապրանքի նկարներ'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
