# Generated by Django 3.2.7 on 2021-10-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20211023_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
