# Generated by Django 3.2.7 on 2021-10-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20211023_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterfield',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
