# Generated by Django 3.2.7 on 2022-05-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20211026_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=False),
        ),
    ]
