# Generated by Django 3.2.7 on 2022-06-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_show_in_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breadcrumbs',
        ),
    ]
