# Generated by Django 3.2.7 on 2022-06-29 19:21

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_delete_breadcrumbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsHomePageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', core.utils.CustomLogoField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Մեր մասին - Գլխավոր էջ',
                'verbose_name_plural': 'Մեր մասին - Գլխավոր էջ',
            },
        ),
    ]
