# Generated by Django 3.2.7 on 2022-07-02 04:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_aboutushomepagetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageUnderSliderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
