# Generated by Django 3.2.7 on 2022-07-02 04:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_homepageunderslidertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageunderslidertext',
            options={'verbose_name': 'Գլխավոր էջի տեքստ', 'verbose_name_plural': 'Գլխավոր էջի տեքստ'},
        ),
        migrations.AddField(
            model_name='homepageunderslidertext',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='homepageunderslidertext',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='homepageunderslidertext',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
