# Generated by Django 3.2.7 on 2022-07-02 12:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20220702_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcategories',
            name='breadcrumbs_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='breadcrumbs_text_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='breadcrumbs_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='authorcategories',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն ազգանուն'),
        ),
        migrations.AddField(
            model_name='authors',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն ազգանուն'),
        ),
        migrations.AddField(
            model_name='authors',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն ազգանուն'),
        ),
        migrations.AddField(
            model_name='authors',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հեղինակի մասին'),
        ),
        migrations.AddField(
            model_name='authors',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հեղինակի մասին'),
        ),
        migrations.AddField(
            model_name='authors',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հեղինակի մասին'),
        ),
    ]
