# Generated by Django 3.2.7 on 2022-07-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20220702_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorcategories',
            options={'verbose_name': 'Բաժին', 'verbose_name_plural': 'Արտիստների բաժիններ'},
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Արտիստ', 'verbose_name_plural': 'Արտիստներ'},
        ),
    ]
