# Generated by Django 3.2.7 on 2022-07-02 13:35

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20220702_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='breadcrumbs_image',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='breadcrumb -ի նկար'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='breadcrumbs_text',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='breadcrumbs_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='breadcrumbs_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='breadcrumbs_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='authorcategories',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_products', to='shop.authors', verbose_name='Հեղինակ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='Բեսթ սելլեր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.Category', verbose_name='Բաժին/բաժիններ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Գույն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.FileField(upload_to='product/', verbose_name='Հիմնական նկար'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Գին'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ապրանքի կոդ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(default=0, verbose_name='Զեղչված գին'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_in_homepage',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել գլխավոր էջում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
    ]
