# Generated by Django 3.2.7 on 2022-07-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20220702_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order'], 'verbose_name': 'Ապրանք', 'verbose_name_plural': 'Ապրանքներ'},
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1, help_text='Քաշը նշել գրամով, որպեսզի հստակ հաշվարկ կատարվի', verbose_name='Ապրանքի քաշ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Գույն'),
        ),
    ]
