# Generated by Django 3.2.7 on 2022-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20220703_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_buying',
            field=models.BooleanField(default=True, verbose_name='Թույլատրելի է ուղիղ վաճառքի'),
        ),
        migrations.AddField(
            model_name='product',
            name='stored_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1, help_text='Քաշը նշել կգ -ով, որպեսզի հստակ հաշվարկ կատարվի', verbose_name='Ապրանքի քաշ'),
        ),
    ]
