# Generated by Django 3.2.7 on 2022-07-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterfield',
            name='two_inputs',
            field=models.BooleanField(default=False, help_text='Այս պարամետրը նախատեսված է չափման միավորների համար', verbose_name='2 մուտքային դաշտ'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='category',
            field=models.ManyToManyField(to='shop.Category', verbose_name='Բաժին/Բաժիններ'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Այս դաշտից կախված փոփոխվում է ապրանքի տիպի արժեքը', verbose_name='Հիմնական դաշտ'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='show_in_filters',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել ֆիլտրերում'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Դաշտի անուն'),
        ),
    ]
