# Generated by Django 3.2.7 on 2022-07-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0047_auto_20220717_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='hide',
            field=models.BooleanField(default=True, verbose_name='Չցուցադրել'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ուղարկողի Հասցե'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Ապրանք'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ՈՒղարկող'),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='text',
            field=models.TextField(verbose_name='Տեքստ'),
        ),
    ]
