# Generated by Django 3.2.7 on 2022-07-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_productreviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
