# Generated by Django 3.2.7 on 2022-07-29 20:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_remove_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='category_image/default.jpg', upload_to='category_image/', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='category',
            name='my_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Դասավորել'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Հայրական բաժին'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել header -ում'),
        ),
        migrations.AlterField(
            model_name='category',
            name='show_in_homepage',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել գլխավոր էջում'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
    ]
