# Generated by Django 3.2.7 on 2022-07-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20220730_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='text',
            new_name='review',
        ),
    ]
