# Generated by Django 3.2.7 on 2022-07-31 16:48

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_rename_text_productreviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Կոդ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='homepageunderslidertext',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='homepageunderslidertext',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='homepageunderslidertext',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='homepageunderslidertext',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.filterfield', verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Գին'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Ապրանք'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.filtervalue', verbose_name='Դաշտի արժեք'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='product/', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Ապրանք'),
        ),
    ]
