# Generated by Django 3.2.7 on 2022-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20220731_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtervalue',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
    ]
