# Generated by Django 3.2.7 on 2022-06-26 18:18

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_alter_header_id_alter_slider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='icon',
            field=core.utils.CustomLogoField(default=1, upload_to='', verbose_name='Լոգո'),
            preserve_default=False,
        ),
    ]
