# Generated by Django 3.2.7 on 2022-06-26 18:29

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_header_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='icon',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Լոգո'),
        ),
    ]
