# Generated by Django 3.2.7 on 2021-10-20 16:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_auto_20211020_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='text2_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text2_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text2_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
