# Generated by Django 3.2.7 on 2021-10-20 18:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0007_auto_20211020_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_hy', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_title_hy', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_description_hy', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True)),
                ('breadcrumb_image', models.FileField(blank=True, upload_to='')),
                ('breadcrumb_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('breadcrumb_text_hy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('breadcrumb_text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('breadcrumb_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('my_order', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.gallerycategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
