# Generated by Django 3.2.7 on 2021-10-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0010_auto_20211021_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
