# Generated by Django 3.2.7 on 2021-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0011_auto_20211021_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
