# Generated by Django 3.2.7 on 2022-06-26 19:14

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0012_auto_20211028_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('breadcrumb_text', models.TextField(blank=True, null=True)),
                ('breadcrumb_image', core.utils.CustomLogoField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Բլոգի բաժին',
                'verbose_name_plural': 'Բլոգի բաժիններ',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Բլոգ', 'verbose_name_plural': 'Բլոգ'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Տեսադարան', 'verbose_name_plural': 'Տեսադարան'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['my_order'], 'verbose_name': 'Տեսադարանի բաժին', 'verbose_name_plural': 'Տեսադարան բաժիններ'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=core.utils.CustomLogoField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Նյութի վերնագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Նյութի վերնագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Նյութի վերնագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Նյութի վերնագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_hy',
            field=models.TextField(null=True, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Պատասխան'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Հարց'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.gallerycategory', verbose_name='Բաժին'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_image',
            field=models.FileField(blank=True, upload_to='', verbose_name='breadcrumb -ի նկար'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='breadcrumb_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Հղում'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.blogcategory', verbose_name='Բաժին'),
        ),
    ]
