# Generated by Django 3.2.7 on 2022-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0013_auto_20220626_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
