# Generated by Django 3.2.7 on 2022-06-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0014_auto_20220626_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='breadcrumb_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='breadcrumb_text_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='breadcrumb_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_hy',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
