# Generated by Django 3.2.7 on 2022-06-29 19:21

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0016_auto_20220628_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text2_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text2_hy',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text2_ru',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Ակտիվ լինելու դեպքում այս նյութը կցուցադրվի «Մեր մասին» էջում որպես գլխավոր նյութ', verbose_name='Հիմնական նյութ'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='logo',
            field=core.utils.CustomLogoField(default=1, upload_to='', verbose_name='Լոգո'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Հղում'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Վերնագիր'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Տեքստ'),
        ),
    ]
