# Generated by Django 3.2.7 on 2022-07-01 19:44

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0019_auto_20220701_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='logo',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Լոգո'),
        ),
    ]
