# Generated by Django 3.2.7 on 2022-07-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0020_alter_aboutus_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Մեր մասին', 'verbose_name_plural': 'Մեր մասին'},
        ),
    ]
