# Generated by Django 3.2.7 on 2022-07-17 06:09

import ckeditor_uploader.fields
import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0021_alter_aboutus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='large_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ամբողջական նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ նկարագիր'),
        ),
    ]
