# Generated by Django 3.2.7 on 2022-07-30 16:31

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0022_auto_20220717_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['my_order'], 'verbose_name': 'Բլոգ', 'verbose_name_plural': 'Բլոգ'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['my_order'], 'verbose_name': 'Բլոգի բաժին', 'verbose_name_plural': 'Բլոգի բաժիններ'},
        ),
        migrations.AddField(
            model_name='blog',
            name='my_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Դասավորել'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Դասավորել'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_image',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='breadcrumb -ի նկար'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='breadcrumb_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='breadcrumb -ի տեքստ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name_hy',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում'),
        ),
    ]
