# Generated by Django 3.2.7 on 2022-07-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0024_auto_20220730_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussocialicons',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutussocialicons',
            name='url',
            field=models.CharField(max_length=400, verbose_name='Հղում'),
        ),
    ]
