# Generated by Django 3.2.7 on 2022-07-30 18:14

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0025_auto_20220730_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutussocialicons',
            name='icon',
            field=core.utils.CustomLogoField(upload_to=''),
        ),
    ]
