# Generated by Django 3.2.7 on 2021-10-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_description',
        ),
    ]
