# Generated by Django 3.2.7 on 2022-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='features',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
