# Generated by Django 3.2.7 on 2022-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_alter_companyinformation_id_alter_footercategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritems',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել միայն մուտք գործած օգտատերերին'),
        ),
    ]
