# Generated by Django 3.2.7 on 2022-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_footeritems_is_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footeritems',
            name='is_auth',
        ),
    ]
