# Generated by Django 3.2.7 on 2022-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0006_remove_footeritems_is_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritems',
            name='is_auth',
            field=models.CharField(choices=[('logged', 'Օգտատերեր'), ('guests', 'Հյուրեր')], default=1, max_length=120, verbose_name='Ցուցադրել միայն մուտք գործած օգտատերերին'),
            preserve_default=False,
        ),
    ]
