# Generated by Django 3.2.7 on 2022-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0007_footeritems_is_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeritems',
            name='is_auth',
            field=models.CharField(blank=True, choices=[('logged', 'Օգտատերեր'), ('guests', 'Հյուրեր')], max_length=120, null=True, verbose_name='Ցուցադրել միայն մուտք գործած օգտատերերին'),
        ),
    ]
