# Generated by Django 3.2.7 on 2022-06-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0008_alter_footeritems_is_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='name_hy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Դաշտի անուն'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='text_hy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Տեքստ'),
        ),
    ]
