# Generated by Django 3.2.7 on 2022-06-25 20:26

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0011_footerinformationtext_footerpartners'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('icon', core.utils.CustomLogoField(upload_to='')),
            ],
            options={
                'verbose_name': 'Վճարային քարտի լոգո',
                'verbose_name_plural': 'Վճարային քարտերի լոգոներ',
            },
        ),
    ]
