# Generated by Django 3.2.7 on 2022-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0012_cardicons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerpartners',
            options={'ordering': ['my_order'], 'verbose_name': 'Գործընկեր', 'verbose_name_plural': 'Գործընկերներ'},
        ),
        migrations.AddField(
            model_name='footerpartners',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
