# Generated by Django 3.2.7 on 2022-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0014_auto_20220729_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinformationtext',
            name='text',
            field=models.TextField(verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='footerinformationtext',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='footerinformationtext',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='footerinformationtext',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Տեքստ'),
        ),
    ]
