# Generated by Django 3.2.7 on 2022-07-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0015_auto_20220729_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='icon',
        ),
    ]
