# Generated by Django 3.2.7 on 2022-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0011_alter_breadcrumbtexts_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title_en',
        ),
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title_hy',
        ),
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title_ru',
        ),
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='location',
            field=models.CharField(choices=[('sale', 'Ակցիա'), ('new_products', 'Նորույթ'), ('best_seller', 'Հատուկ առաջարկ'), ('categories', 'Բաժինների էջ'), ('brands', 'Բրենդների էջ'), ('blog', 'Բլոգ'), ('gallery', 'Տեսադարան'), ('contacts', 'Կապ'), ('authors', 'Արտիստներ'), ('faq', 'Հաճախակի տրվող հարցեր'), ('machanents_tv', 'Machanents TV')], max_length=150, unique=True, verbose_name='Ընտրեք էջը'),
        ),
    ]
