# Generated by Django 3.2.7 on 2021-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('delivery', 'delivery'), ('take', 'take')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Deliveried', 'Deliveried'), ('Canceled', 'Canceled'), ('Unpaid', 'Unpaid')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('cashe', 'cashe'), ('in_market', 'in_market')], default='credit_card', max_length=30),
        ),
    ]
