# Generated by Django 3.2.7 on 2021-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211017_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
