# Generated by Django 3.2.7 on 2021-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_country_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('delivery', 'Առաքում'), ('take', 'Կվերցնեմ ինքս')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Վճարված'), ('Deliveried', 'Առաքված'), ('Canceled', 'Չեղարկված'), ('Unpaid', 'Չվճարված')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.CharField(choices=[('credit_card', 'Անկանխիկ (ARCA/ VISA/ MASTERCARD)'), ('cashe', 'Կանխիկ առաքման պահին'), ('in_market', 'Կանխիկ տեղում')], default='credit_card', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
