# Generated by Django 3.2.7 on 2021-10-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20211017_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('delivery', 'Առաքում'), ('take', 'Կվերցնեմ ինքս')], default='Առաքում', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Paid', 'Վճարված'), ('Deliveried', 'Առաքված'), ('Canceled', 'Չեղարկված'), ('Unpaid', 'Չվճարված'), ('in_progress', 'Ընթացքի մեջ')], default='Ընթացքի մեջ', max_length=130),
        ),
        migrations.AlterField(
            model_name='order',
            name='payments',
            field=models.CharField(choices=[('credit_card', 'Անկանխիկ (ARCA/ VISA/ MASTERCARD)'), ('cashe', 'Կանխիկ առաքման պահին'), ('in_market', 'Կանխիկ տեղում')], default='Անկանխիկ (ARCA/ VISA/ MASTERCARD)', max_length=130),
        ),
    ]
