# Generated by Django 3.2.7 on 2021-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211018_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='title_en',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_hy',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='title_en',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='title_hy',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttypes',
            name='title_en',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttypes',
            name='title_hy',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttypes',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
