# Generated by Django 3.2.7 on 2021-10-20 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20211018_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
