# Generated by Django 3.2.7 on 2021-10-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_orderitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
