# Generated by Django 3.2.7 on 2021-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
