# Generated by Django 3.2.7 on 2022-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_city'),
        ('order', '0024_alter_order_bank_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_hy', models.CharField(max_length=150, null=True)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('round_maark', models.FloatField(blank=True, help_text='Կլորացվող թիվ , օրինակ USA -ի ժամանակ 0.5', null=True)),
                ('every_rounded_price', models.FloatField(blank=True, help_text='Ամեն կլորացվող թվի համար հաշվարկվող գումար', null=True)),
                ('fixes_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Երկերներ',
                'verbose_name_plural': 'Երկերներ',
            },
        ),
        migrations.CreateModel(
            name='FixedValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_gramm', models.FloatField(help_text='Ֆիսված կգ ,օր՝ 3,5', verbose_name='Ֆիքսված քաշ')),
                ('fixed_price', models.FloatField(help_text='Ֆիսված արժեք ,օր՝ 11․500 (արժեքը նշել ՀՀ դրամով)', verbose_name='Ֆիքսված արժեք')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('session_key', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50)),
                ('total_price', models.FloatField(blank=True, default=0)),
                ('delivery_price', models.FloatField(blank=True, default=0)),
                ('all_total', models.FloatField(blank=True, default=0)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_exists', models.BooleanField(default=False, help_text='Ակտիվացնելով այս դաշտը հարցումը հասանելի կլինի վճարման', verbose_name='Պահեստում առկա է')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_hy', models.CharField(max_length=120, null=True)),
                ('name_ru', models.CharField(max_length=120, null=True)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('del_up', models.BooleanField(default=False, help_text='20 կգ ից բարձր առաքքումը գործում է։')),
            ],
            options={
                'verbose_name': 'Մարզեր',
                'verbose_name_plural': 'Մարզեր',
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('round_maark', models.FloatField(blank=True, help_text='Կլորացվող թիվ , օրինակ USA -ի ժամանակ 0.5', null=True)),
                ('every_rounded_price', models.FloatField(blank=True, help_text='Ամեն կլորացվող թվի համար հաշվարկվող գումար', null=True)),
                ('fixed_price', models.FloatField(blank=True, help_text='Այս դաշտում նշում ենք այն արժեքը , որը համապատասխանում է մինիմալ միջակայքին։', null=True)),
            ],
            options={
                'verbose_name': 'Զոնաներ',
                'verbose_name_plural': 'Զոնաներ',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state_name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_of_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_of_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='DeliveryTime',
        ),
    ]
