# Generated by Django 3.2.7 on 2022-07-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220703_1618'),
        ('order', '0025_auto_20220703_1618'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='regions',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.countries'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.delivery'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.paymenttypes'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedvalues',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.countries'),
        ),
        migrations.AddField(
            model_name='countries',
            name='zonas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.zonas'),
        ),
    ]
