# Generated by Django 3.2.7 on 2022-07-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20220703_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.countries'),
        ),
    ]
