# Generated by Django 3.2.7 on 2022-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_regions_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
