# Generated by Django 3.2.7 on 2022-07-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20220710_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='is_expired',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
