# Generated by Django 3.2.7 on 2022-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_productrequest_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='curr_code',
            field=models.CharField(blank=True, default='AMD', max_length=5, null=True),
        ),
    ]
