# Generated by Django 3.2.7 on 2022-07-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_product_product_code'),
        ('order', '0031_productrequest_curr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.productrequest')),
            ],
        ),
    ]
