# Generated by Django 3.2.7 on 2022-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_productrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestitem',
            name='item_total_price',
            field=models.FloatField(default=0),
        ),
    ]
