# Generated by Django 3.2.7 on 2022-07-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_productrequestitem_item_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
