# Generated by Django 3.2.7 on 2022-07-10 19:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_productrequestitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
