# Generated by Django 3.2.7 on 2022-07-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_productrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestitem',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
