# Generated by Django 3.2.7 on 2022-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_productrequestitem_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestitem',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
