# Generated by Django 3.2.7 on 2022-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_productrequestitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
