# Generated by Django 3.2.7 on 2022-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_productrequestitem_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequestitem',
            name='description',
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='features',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
