# Generated by Django 3.2.7 on 2022-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20220713_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestitem',
            name='_product_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ապրանքի Id'),
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Ուղարկել email'),
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Թրեքինգ կոդ'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Առկա քանակություն'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='item_total_price',
            field=models.FloatField(default=0, verbose_name='Ընդհանուր արժեք'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ապրանքի կոդ'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ապրանքի նկար'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Ապրանքի անուն'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Ապրանքի գին'),
        ),
        migrations.AlterField(
            model_name='productrequestitem',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Պատվիրված քանակություն'),
        ),
    ]
