# Generated by Django 3.2.7 on 2022-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20220714_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='uuid_field',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='uuid_field',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
